### ISSUE TITLE
ドキュメント内でリンクされているWikipediaサイトの言語について

### ISSUE THREAD

**Issue by ghost** [hshindo/julia-doc-ja-v0.6#12]
現時点で邦訳されている文章を見てみると、随所にリンクされているWikipediaのサイトが未だに英語版のままですが、Wikipedia日本語版のリンクに張り直した方が良いではないでしょうか。

**Comment by hshindo** [comment]
リンクを日本語版に修正するとしても，後から一括修正できそうなので，ひとまずそのままにしていますが，いかがでしょうか？

**Comment by hshindo** [comment]
では，リンクの修正もお願いします．

**Comment by ghost** [comment]
返信遅れて申し訳ありません。諒解しました。
